### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by niccokunzmann** [xjcl/mundraub-unofficial#1]
Hi,

you linked to your source code, so I had a little look.
I added a Related Work Section: https://github.com/niccokunzmann/mundraub-android/blob/master/README.md

Also: If you would like to upload markers, we can share code - just take mine or create a library for that - if that is possible. Mundraub maybe has no official API, yet. I work with the Drupal Website - not a nice experience.
Also, I envision an integration of "all fruit maps" which means to create a common API for all fruit maps and a server which integrates these. Some work has been done with that.

You can also just take my app and work on it - but that might not be what makes you happy.

**Comment by xjcl** [comment]
Hey Nicco, 

thanks a lot for coming over and having a look! And for adding the link.

Part of my goal with the app was to teach myself Kotlin, not Java, so I think a collaboration / shared library would not be the ideal path forward. I also think it might make sense to go into a gamification direction with my app (collect all fruit types, compare with your friends, etc.).

The common API/code idea sounds interesting, but I feel like that would require a lot of work, and might make people unhappy about having to throw away the code they worked on a lot or even paid for. I would join a Teams/Slack channel though if something gets organized on that topic.

Greetings 
Jan
